// scripts/sunny-on-dark.mjs
// ─────────────────────────────────────────────────────────────────────────────
// Sunny for the dark funnel panel: the kit's files, behind the kit's die-cut.
// ─────────────────────────────────────────────────────────────────────────────
// Sunny's outline is brand-ink, so on loop-navy it vanishes. The brand rule
// (sunny-kit docs/sunny.md, "On dark backgrounds", 2026-10-08) is a white
// die-cut border, never a recoloured outline. This wraps each drawing,
// untouched, in the kit's DIECUT filter (sunny-kit scripts/readme-art.mjs)
// and writes public/brand/<name>-on-dark.svg.
//
//   node scripts/sunny-on-dark.mjs          write the files
//   node scripts/sunny-on-dark.mjs --check  fail if they are out of date
//
// tests/unit/brand.test.ts runs the check, so an updated drawing can't ship
// without its dark twin.
// ─────────────────────────────────────────────────────────────────────────────

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'brand');
export const SOURCES = ['sunny', 'sunny-delighted'];

/** The kit's DIECUT, verbatim apart from the id and the radius's units. */
const diecut = (id, r) => `<filter id="${id}" x="-20%" y="-20%" width="140%" height="140%">
  <feMorphology in="SourceAlpha" operator="dilate" radius="${(r * 0.55).toFixed(2)}"/>
  <feGaussianBlur stdDeviation="${(r * 0.45).toFixed(2)}"/>
  <feComponentTransfer result="grown"><feFuncA type="linear" slope="6" intercept="-1.2"/></feComponentTransfer>
  <feFlood flood-color="#FFFFFF"/><feComposite in2="grown" operator="in" result="halo"/>
  <feMerge><feMergeNode in="halo"/><feMergeNode in="SourceGraphic"/></feMerge>
</filter>`;

export function onDark(svg, name) {
  const open = svg.match(/<svg\b[^>]*>/);
  const vb = open?.[0].match(/viewBox="([^"]+)"/)?.[1];
  if (!open || !vb) throw new Error(`${name}: no <svg viewBox>`);
  const [x, y, w, h] = vb.trim().split(/[\s,]+/).map(Number);
  // A border about 2.5% of the drawing's width: the sign-off's weight at README size.
  const r = w * 0.025;
  const pad = r * 2;
  const inner = svg.slice(open.index + open[0].length, svg.lastIndexOf('</svg>')).replace(/<title>[\s\S]*?<\/title>/, '');
  const id = `${name}-diecut`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x - pad} ${y - pad} ${w + 2 * pad} ${h + 2 * pad}">`
    + `<title>Sunny, the Mole mascot</title>`
    + `<!-- Generated by scripts/sunny-on-dark.mjs from ${name}.svg. Do not edit. -->`
    + `<defs>${diecut(id, r)}</defs>`
    + `<g filter="url(#${id})"><svg x="${x}" y="${y}" width="${w}" height="${h}" viewBox="${vb}">${inner}</svg></g>`
    + `</svg>\n`;
}

export function build() {
  return SOURCES.map(name => ({
    file: join(root, `${name}-on-dark.svg`),
    content: onDark(readFileSync(join(root, `${name}.svg`), 'utf8'), name),
  }));
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const { file, content } of build()) {
    let current = '';
    try { current = readFileSync(file, 'utf8'); } catch { /* missing */ }
    if (current === content) continue;
    if (check) { stale++; console.error(`✗ ${file} is out of date: run node scripts/sunny-on-dark.mjs`); }
    else { writeFileSync(file, content); console.log(`wrote ${file}`); }
  }
  process.exit(stale ? 1 : 0);
}
